name: UI Suite
on:
  workflow_dispatch:
    inputs:
      ENV_NAME:
        type: 'choice'
        description: 'Environment to use'
        required: true
        options:
          - prod
          - dev
          - qa
        default: 'qa'
      THREAD_COUNT:
        type: 'choice'
        description: 'Choose Thread Count'
        required: false
        options:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
        default: 0
  schedule:
    - cron: '30 3 * * *'
concurrency:
  group: uiSuite
  cancel-in-progress: false

jobs:
  run-ui-suite-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      pull-requests: write

    env:
      USE_ENV: ${{github.event.inputs.ENV_NAME || 'qa'}}

    steps:
      - name: Pull the project into the runner
        uses: actions/checkout@v3

      - name: Set system time zone to IST
        run: echo "TZ=Asia/Kolkata" >> $GITHUB_ENV

      - name: Print current date and time (for debugging)
        run: date

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: restore

      - name: Run UI Suite Tests
        continue-on-error: true
        run: mvn clean test -Pui -Dmaven.test.failure.ignore=true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ui=suite-reports
          path: reports

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: save
